### ISSUE TITLE
Working together for a official camel-consul component

### ISSUE THREAD

**Issue by lburgazzoli** [bprager/camel-consul#1]
Hi 

I'm working on a [camel-component](https://github.com/lburgazzoli/lb-camel/tree/master/camel-consul) which shoud cover most of the features consul offers and my plan is to push it pstream to camel repository once done.

Would you take into account to contribute your Consul registry to my repository once my camel-consul will be closed to be ready ?

**Comment by bprager** [comment]
Sure. It would be my pleasure.

**Comment by lburgazzoli** [comment]
Great !

Looking a little bit at your code, the main difference is tat I use https://github.com/OrbitzWorldwide/consul-client but I do not think it would make a big difference, are you ok to change such component ?

**Comment by bprager** [comment]
Let me have a look at the Orbitz library. They use Values, so I have to 
change my models a little.

Should not be that difficult though.

Cheers,

-- Bernd

**Comment by bprager** [comment]
@lburgazzoli : I made all the required changes. We should be good to go.

**Comment by lburgazzoli** [comment]
great !

I've pushed my work in Apache Camel so if you have an Apache JIRA Account please raise an issue and send a PR, I will take care to merge it.

**Comment by bprager** [comment]
I opened the JIRA issue [CAMEL-992](https://issues.apache.org/jira/browse/CAMEL-9992). I hope I provided sufficient info. (It's the first time I have done this.)

**Comment by lburgazzoli** [comment]
@bprager thank you for your contribution
